name: amy
description: AMY A Meal by You.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  provider: ^6.0.2
  firebase_core: ^1.12.0
  flutter_spinkit: ^5.1.0
  firebase_app_check: ^0.0.6+5
  confetti: ^0.6.0
  carousel_slider: ^4.0.0
  

flutter_icons:
  image_path: "assets/app_logo.png" 
  android: true
  ios: true
  web: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/amy_logo.png
    - assets/qr.png
    - assets/images/bg1.png
    - assets/images/breakfast.png
    - assets/images/hands.jpg
    - assets/images/kid_bread.png
    - assets/images/kid_plate.jpg
    - assets/images/kid_scarffed.png
    - assets/images/knife_fork.jpg
    - assets/Amy/1.png
    - assets/Amy/1.gif
    - assets/Amy/2.png
    - assets/Amy/3.png
    - assets/Amy/4.png
    - assets/Amy/5.png
    - assets/gif/confetti.gif
    - assets/Food/breakfast.png
    - assets/Food/breakfast2.png
    - assets/Food/breakfast3.png
    - assets/Food/lunch.png
    - assets/Food/lunch 2.png
    - assets/Food/lunch 3.png
    - assets/Food/dinner.png
    - assets/Food/dinner 2.png
    - assets/Food/dinner 3.png
    - assets/Minds/jayati.png
    - assets/Minds/pranav.png
    - assets/Minds/madhav.png




  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Caveat
      fonts:
        - asset: assets/fonts/CaveatBrush-Regular.ttf
          weight: 700

    - family: Playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 700
    
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
