// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjO2JQla3ysSPQNEGWiFjBEdzlGULOgCo',
    appId: '1:542220855483:web:4648ea81c9866ee336219e',
    messagingSenderId: '542220855483',
    projectId: 'amy-a-meal-by-me',
    authDomain: 'amy-a-meal-by-me.firebaseapp.com',
    storageBucket: 'amy-a-meal-by-me.appspot.com',
    measurementId: 'G-PMQYXG3Q2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8bWYrirDXyC43M6tqprxJauFy_4s5OKQ',
    appId: '1:542220855483:android:294294c9eb574fc336219e',
    messagingSenderId: '542220855483',
    projectId: 'amy-a-meal-by-me',
    storageBucket: 'amy-a-meal-by-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwCPRBuvBl7c1u04Q-THXwpgt1hAOHodQ',
    appId: '1:542220855483:ios:ffef53c67e6900da36219e',
    messagingSenderId: '542220855483',
    projectId: 'amy-a-meal-by-me',
    storageBucket: 'amy-a-meal-by-me.appspot.com',
    iosClientId: '542220855483-d0osgdjovaipfotljr5dgnh6ooj3iban.apps.googleusercontent.com',
    iosBundleId: 'com.example.amy',
  );
}
